version: '3.9'

services:
  # MongoDB
  mongo_db:
    image: mongo:4.4.6
    restart: always
    volumes:
      - mongo_db:/data/db
    logging:
      driver: none


  api:
    build: .
    ports:
      - 80:3000
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017
      DBNAME: site2api
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
